### ISSUE TITLE
svg解析v1.2报错：attempt to index field 'g' (a nil value)

### ISSUE THREAD

**Issue by emako** [dumpling233/aegisub_Automation#1]

**Comment by emako** [comment]
Lua reported a runtime error:
    File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 578
<anonymous function at lines 578-577>
    File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 464
svg2ass
    File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 390
htmlParser
attempt to index field 'g' (a nil value)

SVG内容：
`<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1616281910759" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1843" width="36" height="36" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><style type="text/css"></style></defs><path d="M896.864 315.744l-30.72 30.72c-66.56-58.016-151.904-90.464-240.64-90.464-59.744 0-119.456 15.36-170.656 42.656l129.696-129.696c10.24 6.816 22.176 10.24 34.144 10.24 17.056 0 34.144-6.816 47.776-20.48 27.296-27.296 27.296-69.984 0-97.28-13.664-13.664-30.72-20.48-47.776-20.48s-34.144 6.816-47.776 20.48c-22.176 23.904-25.6 58.016-10.24 83.616l-163.84 163.84-30.72-30.72-83.616 83.616 30.72 30.72-167.264 167.264c-10.24-6.816-22.176-10.24-34.144-10.24-17.056 0-34.144 6.816-47.776 20.48-27.296 27.296-27.296 69.984 0 97.28 13.664 11.936 30.72 18.784 47.776 18.784s34.144-6.816 47.776-20.48c22.176-22.176 25.6-56.32 10.24-83.616l129.696-129.696c-68.256 131.424-52.896 295.264 47.776 411.296l-30.72 32.416 85.344 83.616 83.616-83.616-83.616-83.616-29.024 29.024c-98.976-116.064-104.096-283.296-20.48-406.176l13.664 13.664 85.344-83.616-15.36-13.664c54.624-39.264 121.184-59.744 189.44-59.744 80.224 0 155.296 29.024 216.736 80.224l-30.72 29.024 85.344 83.616 83.616-83.616-83.616-85.344zM437.76 896l-35.84 35.84-35.84-35.84 35.84-35.84 35.84 35.84zM594.784 87.04c6.816-6.816 15.36-10.24 23.904-10.24s17.056 3.424 23.904 10.24c13.664 13.664 13.664 34.144 0 47.776-6.816 6.816-15.36 10.24-23.904 10.24s-17.056-3.424-23.904-10.24c-13.664-11.936-13.664-34.144 0-47.776zM135.68 641.696c-6.816 6.816-15.36 10.24-23.904 10.24s-17.056-3.424-23.904-10.24c-6.816-5.12-10.24-13.664-10.24-23.904 0-8.544 3.424-17.056 10.24-23.904s15.36-10.24 23.904-10.24c8.544 0 17.056 3.424 23.904 10.24 13.664 13.664 13.664 35.84 0 47.776zM364.384 401.056l-35.84-35.84 35.84-35.84 35.84 35.84-35.84 35.84zM896.864 436.896l-35.84-35.84 35.84-35.84 35.84 35.84-35.84 35.84z" p-id="1844"></path></svg>`

**Comment by dumpling233** [comment]
> Lua reported a runtime error:
> File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 578
> <anonymous function at lines 578-577>
> File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 464
> svg2ass
> File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 390
> htmlParser
> attempt to index field 'g' (a nil value)
> 
> SVG内容：
> `<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1616281910759" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1843" width="36" height="36" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><style type="text/css"></style></defs><path d="M896.864 315.744l-30.72 30.72c-66.56-58.016-151.904-90.464-240.64-90.464-59.744 0-119.456 15.36-170.656 42.656l129.696-129.696c10.24 6.816 22.176 10.24 34.144 10.24 17.056 0 34.144-6.816 47.776-20.48 27.296-27.296 27.296-69.984 0-97.28-13.664-13.664-30.72-20.48-47.776-20.48s-34.144 6.816-47.776 20.48c-22.176 23.904-25.6 58.016-10.24 83.616l-163.84 163.84-30.72-30.72-83.616 83.616 30.72 30.72-167.264 167.264c-10.24-6.816-22.176-10.24-34.144-10.24-17.056 0-34.144 6.816-47.776 20.48-27.296 27.296-27.296 69.984 0 97.28 13.664 11.936 30.72 18.784 47.776 18.784s34.144-6.816 47.776-20.48c22.176-22.176 25.6-56.32 10.24-83.616l129.696-129.696c-68.256 131.424-52.896 295.264 47.776 411.296l-30.72 32.416 85.344 83.616 83.616-83.616-83.616-83.616-29.024 29.024c-98.976-116.064-104.096-283.296-20.48-406.176l13.664 13.664 85.344-83.616-15.36-13.664c54.624-39.264 121.184-59.744 189.44-59.744 80.224 0 155.296 29.024 216.736 80.224l-30.72 29.024 85.344 83.616 83.616-83.616-83.616-85.344zM437.76 896l-35.84 35.84-35.84-35.84 35.84-35.84 35.84 35.84zM594.784 87.04c6.816-6.816 15.36-10.24 23.904-10.24s17.056 3.424 23.904 10.24c13.664 13.664 13.664 34.144 0 47.776-6.816 6.816-15.36 10.24-23.904 10.24s-17.056-3.424-23.904-10.24c-13.664-11.936-13.664-34.144 0-47.776zM135.68 641.696c-6.816 6.816-15.36 10.24-23.904 10.24s-17.056-3.424-23.904-10.24c-6.816-5.12-10.24-13.664-10.24-23.904 0-8.544 3.424-17.056 10.24-23.904s15.36-10.24 23.904-10.24c8.544 0 17.056 3.424 23.904 10.24 13.664 13.664 13.664 35.84 0 47.776zM364.384 401.056l-35.84-35.84 35.84-35.84 35.84 35.84-35.84 35.84zM896.864 436.896l-35.84-35.84 35.84-35.84 35.84 35.84-35.84 35.84z" p-id="1844"></path></svg>`

目前对svg格式的节点判断比较严格，请把你会出问题的svg文件使用https://www.vectorizer.io/这个网站转换一遍，这样生成的svg文件应该是绝对不会出问题的

> Lua reported a runtime error:
> File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 578
> <anonymous function at lines 578-577>
> File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 464
> svg2ass
> File "D:/AvsQmod\tools\Aegisub\automation\autoload\svg解析v1.2.lua", line 390
> htmlParser
> attempt to index field 'g' (a nil value)
> 
> SVG内容：
> `<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1616281910759" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1843" width="36" height="36" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><style type="text/css"></style></defs><path d="M896.864 315.744l-30.72 30.72c-66.56-58.016-151.904-90.464-240.64-90.464-59.744 0-119.456 15.36-170.656 42.656l129.696-129.696c10.24 6.816 22.176 10.24 34.144 10.24 17.056 0 34.144-6.816 47.776-20.48 27.296-27.296 27.296-69.984 0-97.28-13.664-13.664-30.72-20.48-47.776-20.48s-34.144 6.816-47.776 20.48c-22.176 23.904-25.6 58.016-10.24 83.616l-163.84 163.84-30.72-30.72-83.616 83.616 30.72 30.72-167.264 167.264c-10.24-6.816-22.176-10.24-34.144-10.24-17.056 0-34.144 6.816-47.776 20.48-27.296 27.296-27.296 69.984 0 97.28 13.664 11.936 30.72 18.784 47.776 18.784s34.144-6.816 47.776-20.48c22.176-22.176 25.6-56.32 10.24-83.616l129.696-129.696c-68.256 131.424-52.896 295.264 47.776 411.296l-30.72 32.416 85.344 83.616 83.616-83.616-83.616-83.616-29.024 29.024c-98.976-116.064-104.096-283.296-20.48-406.176l13.664 13.664 85.344-83.616-15.36-13.664c54.624-39.264 121.184-59.744 189.44-59.744 80.224 0 155.296 29.024 216.736 80.224l-30.72 29.024 85.344 83.616 83.616-83.616-83.616-85.344zM437.76 896l-35.84 35.84-35.84-35.84 35.84-35.84 35.84 35.84zM594.784 87.04c6.816-6.816 15.36-10.24 23.904-10.24s17.056 3.424 23.904 10.24c13.664 13.664 13.664 34.144 0 47.776-6.816 6.816-15.36 10.24-23.904 10.24s-17.056-3.424-23.904-10.24c-13.664-11.936-13.664-34.144 0-47.776zM135.68 641.696c-6.816 6.816-15.36 10.24-23.904 10.24s-17.056-3.424-23.904-10.24c-6.816-5.12-10.24-13.664-10.24-23.904 0-8.544 3.424-17.056 10.24-23.904s15.36-10.24 23.904-10.24c8.544 0 17.056 3.424 23.904 10.24 13.664 13.664 13.664 35.84 0 47.776zM364.384 401.056l-35.84-35.84 35.84-35.84 35.84 35.84-35.84 35.84zM896.864 436.896l-35.84-35.84 35.84-35.84 35.84 35.84-35.84 35.84z" p-id="1844"></path></svg>`

目前对svg格式的节点判断比较严格，请把你会出问题的svg文件使用https://www.vectorizer.io/这个网站转换一遍，这样生成的svg文件应该是绝对不会出问题的

**Comment by emako** [comment]
对比了一下https://www.vectorizer.io/得到的path，是因为数值之间负号-在浏览器里可以不用空格隔开

**Comment by emako** [comment]
> 对比了一下[https://www.vectorizer.io/得到的path，是因为数值之间负号-在浏览器里可以不用空格隔开](https://www.vectorizer.io/%E5%BE%97%E5%88%B0%E7%9A%84path%EF%BC%8C%E6%98%AF%E5%9B%A0%E4%B8%BA%E6%95%B0%E5%80%BC%E4%B9%8B%E9%97%B4%E8%B4%9F%E5%8F%B7-%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E9%87%8C%E5%8F%AF%E4%BB%A5%E4%B8%8D%E7%94%A8%E7%A9%BA%E6%A0%BC%E9%9A%94%E5%BC%80)

转换path前，把path替换一下就OK了，"-"替换成" -"
